// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWs2nXEhyA2DLHMuiQAI2sNJCJo372JWI',
    appId: '1:936316195806:web:41c7397563e1a71c13034f',
    messagingSenderId: '936316195806',
    projectId: 'newstrust-fall',
    authDomain: 'newstrust-fall.firebaseapp.com',
    storageBucket: 'newstrust-fall.firebasestorage.app',
    measurementId: 'G-PBDYVMWKK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw_h_PbO8dcc74rDjbP-BekSgzMmXmHF8',
    appId: '1:936316195806:android:807efa159f810ef113034f',
    messagingSenderId: '936316195806',
    projectId: 'newstrust-fall',
    storageBucket: 'newstrust-fall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGXDCmRFI4KDrECk09KZXQW6ifjF4Zmag',
    appId: '1:936316195806:ios:4090b9b840f368d913034f',
    messagingSenderId: '936316195806',
    projectId: 'newstrust-fall',
    storageBucket: 'newstrust-fall.firebasestorage.app',
    iosBundleId: 'com.example.fypProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGXDCmRFI4KDrECk09KZXQW6ifjF4Zmag',
    appId: '1:936316195806:ios:4090b9b840f368d913034f',
    messagingSenderId: '936316195806',
    projectId: 'newstrust-fall',
    storageBucket: 'newstrust-fall.firebasestorage.app',
    iosBundleId: 'com.example.fypProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWs2nXEhyA2DLHMuiQAI2sNJCJo372JWI',
    appId: '1:936316195806:web:5926ad024856cd7f13034f',
    messagingSenderId: '936316195806',
    projectId: 'newstrust-fall',
    authDomain: 'newstrust-fall.firebaseapp.com',
    storageBucket: 'newstrust-fall.firebasestorage.app',
    measurementId: 'G-PDYB9SLPF8',
  );
}
